# -*- coding: utf-8 -*-
"""LinearRegression_Normal_eqn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCyKm9CTfFaF2c5tzZv34Y8hFpVj6qQf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data=fetch_california_housing(as_frame=True)

df =data.frame
print("Dataset Shape",df.shape)
df.head()

x=df[["AveRooms"]]
y=df[["MedHouseVal"]]
print("Input Features")
display(x.head())
print("Output Features")
display(y.head())

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model =LinearRegression()
model.fit(x_train,y_train)

print("Intercept:", round(model.intercept_[0], 4))
print("Slope:", round(model.coef_[0][0], 4))
print(f"\nHouse Price = {model.intercept_[0]:.4f} + ({model.coef_[0][0]:.4f} * AveRooms)")

y_pred=model.predict(x_test)
print(y_pred[:10])

mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error:",mse)
print("R-squared:",r2)

plt.figure(figsize=(10,6))
plt.scatter(x_test,y_test,color='blue',label='Actual',alpha=.4)
x_sorted=x_test.sort_values('AveRooms')
plt.plot(x_sorted,model.predict(x_sorted),color='Green',linewidth=2,label="Regression Line")
plt.xlabel("AveRooms")
plt.ylabel("MedHouseVal")
plt.title("House Price Prediction")
plt.legend()
plt.show()